version = 1

[approve]
auto_approve_usernames = ["dependabot"]

[merge]
automerge_label = "automerge 🚀"

[merge.automerge_dependencies]
usernames = ["dependabot"]
versions = ["major", "minor", "patch"]

[merge.message]
include_coauthors = true
include_pull_request_url = true
title = "pull_request_title"
