# Configuration file for pre-commit (https://pre-commit.com/)
# Please run `pre-commit run --all-files` when adding or changing entries.

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        types: [python]
        language: system
        stages: [commit]

      - id: gitlint
        name: gitlint
        entry: gitlint
        args: [--msg-filename]
        language: system
        stages: [commit-msg]

      - id: isort
        name: isort
        entry: isort
        types: [python]
        language: system
        stages: [commit]

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        stages: [commit]
        types_or: [python, pyi]
        require_serial: true

      - id: pathchk
        name: pathchk
        entry: pathchk
        args: [--portability]
        exclude: ^([a-zA-Z0-9._][a-zA-Z0-9._-]+)(/[a-zA-Z0-9._][a-zA-Z0-9._-]+)*$ # https://lists.gnu.org/archive/html/coreutils/2023-01/msg00006.html
        language: system
        stages: [commit]

      - id: pylint
        name: pylint
        entry: pylint
        types: [python]
        language: system
        stages: [commit]
