language: python

python: '3.7'

# always test things that aren't pushes (like PRs)
# never test tags or pushes to non-master branches (wait for PR)
# https://github.com/travis-ci/travis-ci/issues/2200#issuecomment-441395545)
if: type != push OR (tag IS blank AND branch = master)

before_install:
  - pip install -r requirements-dev.txt

install:
  - pip install -r requirements.txt

script:
  - black src/ --check --diff
  - black tests/ --check --diff
  - pylint src/
  - pylint tests/
  - python -m pytest
  - coverage run tests/test_api.py 
  - coverage report -m