service: linz-qgis-s3-plugin-repo

plugins:
  - serverless-python-requirements
  - serverless-wsgi
custom:
  bucket_base_name: "qgis-plugin-repository"
  tableName: 'plugins-table-${self:provider.stage}'
  wsgi:
    app: src/api.app
    packRequirements: false

provider:
  name: aws
  runtime: python3.6
  stage: dev2
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["PluginsDynamoDBTable", "Arn" ] }
  environment:
    REPO_BUCKET_NAME: ${self:custom.bucket_base_name}
    PLUGINS_TABLE: ${self:custom.tableName}

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

resources:
  Resources:
    # Configure Repo Bucket Ploicy
    RepoBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket_base_name}
        AccessControl: PublicReadWrite
    RepoBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref RepoBucket
        PolicyDocument:
          Id: RepoBucketPolicy
          Version: '2012-10-17'
          Statement:
            - Sid: PublicGetObjListBucket
              Effect: Allow
              Principal: '*'
              Action:
                - "s3:*"
                #- "s3:GetObject"
                #- "s3:ListBucket"
              Resource:
                - Fn::Join:
                  - ""
                  - - "arn:aws:s3:::"
                    - "Ref" : "RepoBucket"
                    - '/*'
                - Fn::Join:
                  - ""
                  - - "arn:aws:s3:::"
                    - "Ref" : "RepoBucket"
    PluginsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
          - AttributeName: version
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
          - AttributeName: version
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
