service: linz-qgis-s3-plugin-repo

provider:
  name: aws
  runtime: python3.7

plugins:
  - serverless-python-requirements
  - serverless-wsgi


custom:
  pythonRequirements:
   usePoetry: false
   noDeploy:
      - boto3
      - botocore
  wsgi:
    app: src/api.app

package:
  exclude:
    - ./.venv/**

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

