swagger: "2.0"
info:
  description: "API documnetaion for LINZ QGIS Plugin Repository."
  version: "1.0.0"
  title: "LINZ QGIS plugin repository "
  termsOfService: ""
  contact:
    email: "splanzer@linz.govt.nz"
  license:
    name: "BSD-3-Clause"
    url: "http://www.opensource.org/licenses/BSD-3-Clause"
host: "aws..."
basePath: "/v1"
schemes:
- "https"
- "http"
paths:
  /upload:
    post:
      tags:
      - "plugin"
      summary: "Upload a QGIS Plugin"
      description: "Upload a QGIS Plugin to the repository"
      operationId: "addPlugin"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - in: "formData"
        name: "file"
        description: "Plugin file to be uploaded"
        required: true
        type: file
      responses:
        405:
          description: "Invalid input"
        201:
          description: "plugin upload"
          schema:
            $ref: "#/definitions/ApiResponse"
  /listall/:
    get:
      tags:
      - "plugin"
      summary: "Lists all plugins stored in the repository"
      description: ""
      operationId: "listAllPlugins"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Plugin"
        400:
          description: "Invalid status value"
  /remove/{id}:
    delete:
      tags:
      - "plugin"
      summary: "Removes a plugin from the repository"
      description: ""
      operationId: "deletePlugin"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "plugin id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Plugin not found"
        200:
          description: "Plugin removed"
          schema:
            $ref: "#/definitions/Plugin"
definitions:
  Plugin:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      pluginName:
        type: "string"
      version:
        type: "string"
      author:
        type: "string"
      description:
        type: "string"    
      uploadedDate:
        type: "string"
        format: "date-time"
      experimental:
        type: "boolean"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "source code repository"
  url: "https://github.com/linz/s3-qgis-plugin-repo"