openapi: 3.0.1
info:
  title: 'LINZ QGIS plugin repository '
  description: API documnetaion for LINZ QGIS Plugin Repository.
  termsOfService: ""
  contact:
    email: splanzer@linz.govt.nz
  license:
    name: BSD-3-Clause
    url: http://www.opensource.org/licenses/BSD-3-Clause
  version: 1.0.0
externalDocs:
  description: source code repository
  url: https://github.com/linz/s3-qgis-plugin-repo
servers:
- url: https://aws.../v1
paths:
  /plugin:
    post:
      tags:
      - plugin
      summary: Upload a QGIS Plugin
      description: Upload a QGIS Plugin to the repository
      operationId: addPlugin
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
              properties:
                file:
                  type: string
                  description: Plugin file to be uploaded
                  format: binary
        required: true
      responses:
        201:
          description: plugin upload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        400:
          description: Invalid input
          content: {}
    get:
      tags:
      - plugin
      summary: Lists all plugins stored in the repository
      operationId: listAllPlugins
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plugin'
        400:
          description: Invalid status value
          content: {}
  /plugin/{id}:
    delete:
      tags:
      - plugin
      summary: Removes a plugin from the repository
      operationId: deletePlugin
      parameters:
      - name: id
        in: path
        description: plugin id to delete
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: Plugin removed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plugin'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Plugin not found
          content: {}
components:
  schemas:
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
    Plugin:
      type: object
      properties:
        id:
          type: integer
          format: int64
        pluginName:
          type: string
        version:
          type: string
        author:
          type: string
        description:
          type: string
        uploadedDate:
          type: string
          format: date-time
        experimental:
          type: boolean
