name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Format
        run: |
          black src/ --check --diff
          black tests/ --check --diff

      - name: Lint
        run: |
          pylint src/
          pylint tests/

      - name: Test
        run: python -m pytest
